// todo generate the protobuf code here
// delete the templates code start

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/serverNameExample/v1/userExample.proto

package v1

import (
	types "github.com/Eric-Guo/sponge/api/types"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenderType int32

const (
	GenderType_UNKNOWN GenderType = 0
	GenderType_MALE    GenderType = 1
	GenderType_FEMALE  GenderType = 2
)

// Enum value maps for GenderType.
var (
	GenderType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MALE",
		2: "FEMALE",
	}
	GenderType_value = map[string]int32{
		"UNKNOWN": 0,
		"MALE":    1,
		"FEMALE":  2,
	}
)

func (x GenderType) Enum() *GenderType {
	p := new(GenderType)
	*p = x
	return p
}

func (x GenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_serverNameExample_v1_userExample_proto_enumTypes[0].Descriptor()
}

func (GenderType) Type() protoreflect.EnumType {
	return &file_api_serverNameExample_v1_userExample_proto_enumTypes[0]
}

func (x GenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenderType.Descriptor instead.
func (GenderType) EnumDescriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{0}
}

type CreateUserExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`                                               // name
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email"`                                             // email
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`                                       // password
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone"`                                             // phone number
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar"`                                           // avatar
	Age           int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age"`                                                // age
	Gender        GenderType             `protobuf:"varint,7,opt,name=gender,proto3,enum=api.serverNameExample.v1.GenderType" json:"gender"` // gender, 1:Male, 2:Female, other values:unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserExampleRequest) Reset() {
	*x = CreateUserExampleRequest{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserExampleRequest) ProtoMessage() {}

func (x *CreateUserExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserExampleRequest.ProtoReflect.Descriptor instead.
func (*CreateUserExampleRequest) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserExampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserExampleRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserExampleRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserExampleRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserExampleRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateUserExampleRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserExampleRequest) GetGender() GenderType {
	if x != nil {
		return x.Gender
	}
	return GenderType_UNKNOWN
}

type CreateUserExampleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserExampleReply) Reset() {
	*x = CreateUserExampleReply{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserExampleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserExampleReply) ProtoMessage() {}

func (x *CreateUserExampleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserExampleReply.ProtoReflect.Descriptor instead.
func (*CreateUserExampleReply) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserExampleReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserExampleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserExampleByIDRequest) Reset() {
	*x = DeleteUserExampleByIDRequest{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserExampleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserExampleByIDRequest) ProtoMessage() {}

func (x *DeleteUserExampleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserExampleByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserExampleByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserExampleByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserExampleByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserExampleByIDReply) Reset() {
	*x = DeleteUserExampleByIDReply{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserExampleByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserExampleByIDReply) ProtoMessage() {}

func (x *DeleteUserExampleByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserExampleByIDReply.ProtoReflect.Descriptor instead.
func (*DeleteUserExampleByIDReply) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{3}
}

type UpdateUserExampleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`                                               // name
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`                                             // email
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password"`                                       // password
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone"`                                             // phone number
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar"`                                           // avatar
	Age           int32                  `protobuf:"varint,7,opt,name=age,proto3" json:"age"`                                                // age
	Gender        GenderType             `protobuf:"varint,8,opt,name=gender,proto3,enum=api.serverNameExample.v1.GenderType" json:"gender"` // gender, 1:Male, 2:Female, other values:unknown
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status"`                                          // account status
	LoginAt       int64                  `protobuf:"varint,10,opt,name=loginAt,proto3" json:"loginAt"`                                       // login timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserExampleByIDRequest) Reset() {
	*x = UpdateUserExampleByIDRequest{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserExampleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserExampleByIDRequest) ProtoMessage() {}

func (x *UpdateUserExampleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserExampleByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserExampleByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserExampleByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserExampleByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserExampleByIDRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserExampleByIDRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserExampleByIDRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserExampleByIDRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserExampleByIDRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserExampleByIDRequest) GetGender() GenderType {
	if x != nil {
		return x.Gender
	}
	return GenderType_UNKNOWN
}

func (x *UpdateUserExampleByIDRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserExampleByIDRequest) GetLoginAt() int64 {
	if x != nil {
		return x.LoginAt
	}
	return 0
}

type UpdateUserExampleByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserExampleByIDReply) Reset() {
	*x = UpdateUserExampleByIDReply{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserExampleByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserExampleByIDReply) ProtoMessage() {}

func (x *UpdateUserExampleByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserExampleByIDReply.ProtoReflect.Descriptor instead.
func (*UpdateUserExampleByIDReply) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{5}
}

type UserExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`                                               // name
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`                                             // email
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone"`                                             // phone number
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar"`                                           // avatar
	Age           int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age"`                                                // age
	Gender        GenderType             `protobuf:"varint,7,opt,name=gender,proto3,enum=api.serverNameExample.v1.GenderType" json:"gender"` // gender, 1:Male, 2:Female, other values:unknown
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status"`                                          // account status
	LoginAt       int64                  `protobuf:"varint,9,opt,name=loginAt,proto3" json:"loginAt"`                                        // login timestamp
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt"`                                    // creation time
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt"`                                    // update time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExample) Reset() {
	*x = UserExample{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExample) ProtoMessage() {}

func (x *UserExample) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExample.ProtoReflect.Descriptor instead.
func (*UserExample) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{6}
}

func (x *UserExample) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserExample) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserExample) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserExample) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserExample) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserExample) GetGender() GenderType {
	if x != nil {
		return x.Gender
	}
	return GenderType_UNKNOWN
}

func (x *UserExample) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserExample) GetLoginAt() int64 {
	if x != nil {
		return x.LoginAt
	}
	return 0
}

func (x *UserExample) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserExample) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetUserExampleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserExampleByIDRequest) Reset() {
	*x = GetUserExampleByIDRequest{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserExampleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserExampleByIDRequest) ProtoMessage() {}

func (x *GetUserExampleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserExampleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserExampleByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserExampleByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserExampleByIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserExample   *UserExample           `protobuf:"bytes,1,opt,name=userExample,proto3" json:"userExample"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserExampleByIDReply) Reset() {
	*x = GetUserExampleByIDReply{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserExampleByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserExampleByIDReply) ProtoMessage() {}

func (x *GetUserExampleByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserExampleByIDReply.ProtoReflect.Descriptor instead.
func (*GetUserExampleByIDReply) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserExampleByIDReply) GetUserExample() *UserExample {
	if x != nil {
		return x.UserExample
	}
	return nil
}

type ListUserExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *types.Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserExampleRequest) Reset() {
	*x = ListUserExampleRequest{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserExampleRequest) ProtoMessage() {}

func (x *ListUserExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserExampleRequest.ProtoReflect.Descriptor instead.
func (*ListUserExampleRequest) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserExampleRequest) GetParams() *types.Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListUserExampleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	UserExamples  []*UserExample         `protobuf:"bytes,2,rep,name=userExamples,proto3" json:"userExamples"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserExampleReply) Reset() {
	*x = ListUserExampleReply{}
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserExampleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserExampleReply) ProtoMessage() {}

func (x *ListUserExampleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_serverNameExample_v1_userExample_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserExampleReply.ProtoReflect.Descriptor instead.
func (*ListUserExampleReply) Descriptor() ([]byte, []int) {
	return file_api_serverNameExample_v1_userExample_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserExampleReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserExampleReply) GetUserExamples() []*UserExample {
	if x != nil {
		return x.UserExamples
	}
	return nil
}

var File_api_serverNameExample_v1_userExample_proto protoreflect.FileDescriptor

const file_api_serverNameExample_v1_userExample_proto_rawDesc = "" +
	"\n" +
	"*api/serverNameExample/v1/userExample.proto\x12\x18api.serverNameExample.v1\x1a\x17validate/validate.proto\x1a\x15api/types/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13tagger/tagger.proto\"\xb2\x02\n" +
	"\x18CreateUserExampleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x04name\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\bpassword\x12.\n" +
	"\x05phone\x18\x04 \x01(\tB\x18\xfaB\x15r\x132\x11^1[3456789]\\d{9}$R\x05phone\x12 \n" +
	"\x06avatar\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x06avatar\x12\x1b\n" +
	"\x03age\x18\x06 \x01(\x05B\t\xfaB\x06\x1a\x04\x18x(\x00R\x03age\x12F\n" +
	"\x06gender\x18\a \x01(\x0e2$.api.serverNameExample.v1.GenderTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06gender\"(\n" +
	"\x16CreateUserExampleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"D\n" +
	"\x1cDeleteUserExampleByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02(\x01\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"\x1c\n" +
	"\x1aDeleteUserExampleByIDReply\"\xba\x02\n" +
	"\x1cUpdateUserExampleByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02(\x01\x9a\x84\x9e\x03\buri:\"id\"R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03age\x18\a \x01(\x05R\x03age\x12<\n" +
	"\x06gender\x18\b \x01(\x0e2$.api.serverNameExample.v1.GenderTypeR\x06gender\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x18\n" +
	"\aloginAt\x18\n" +
	" \x01(\x03R\aloginAt\"\x1c\n" +
	"\x1aUpdateUserExampleByIDReply\"\xb3\x02\n" +
	"\vUserExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12<\n" +
	"\x06gender\x18\a \x01(\x0e2$.api.serverNameExample.v1.GenderTypeR\x06gender\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x18\n" +
	"\aloginAt\x18\t \x01(\x03R\aloginAt\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\"A\n" +
	"\x19GetUserExampleByIDRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\x04B\x14\xfaB\x042\x02(\x01\x9a\x84\x9e\x03\buri:\"id\"R\x02id\"b\n" +
	"\x17GetUserExampleByIDReply\x12G\n" +
	"\vuserExample\x18\x01 \x01(\v2%.api.serverNameExample.v1.UserExampleR\vuserExample\"M\n" +
	"\x16ListUserExampleRequest\x123\n" +
	"\x06params\x18\x01 \x01(\v2\x11.api.types.ParamsB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06params\"w\n" +
	"\x14ListUserExampleReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12I\n" +
	"\fuserExamples\x18\x02 \x03(\v2%.api.serverNameExample.v1.UserExampleR\fuserExamples*/\n" +
	"\n" +
	"GenderType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x022\xc2\v\n" +
	"\vuserExample\x12\xfb\x01\n" +
	"\x06Create\x122.api.serverNameExample.v1.CreateUserExampleRequest\x1a0.api.serverNameExample.v1.CreateUserExampleReply\"\x8a\x01\x92Ai\x12\x18Create a new userExample\x1aMCreates a new userExample entity using the provided data in the request body.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/userExample\x12\x84\x02\n" +
	"\n" +
	"DeleteByID\x126.api.serverNameExample.v1.DeleteUserExampleByIDRequest\x1a4.api.serverNameExample.v1.DeleteUserExampleByIDReply\"\x87\x01\x92Ad\x12\x1aDelete a userExample by id\x1aFDeletes a existing userExample identified by the given id in the path.\x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/userExample/{id}\x12\xbb\x02\n" +
	"\n" +
	"UpdateByID\x126.api.serverNameExample.v1.UpdateUserExampleByIDRequest\x1a4.api.serverNameExample.v1.UpdateUserExampleByIDReply\"\xbe\x01\x92A\x97\x01\x12\x1aUpdate a userExample by id\x1ayUpdates the specified userExample with new data provided in the request body. The target is identified by id in the path.\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/userExample/{id}\x12\x83\x02\n" +
	"\aGetByID\x123.api.serverNameExample.v1.GetUserExampleByIDRequest\x1a1.api.serverNameExample.v1.GetUserExampleByIDReply\"\x8f\x01\x92Al\x12\x17Get a userExample by id\x1aQGets detailed information of a userExample specified by the given id in the path.\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/userExample/{id}\x12\xe9\x02\n" +
	"\x04List\x120.api.serverNameExample.v1.ListUserExampleRequest\x1a..api.serverNameExample.v1.ListUserExampleReply\"\xfe\x01\x92A\xd7\x01\x12/get a list of userExamples by custom conditions\x1a\xa3\x01Returns a paginated list of userExamples filtered by specified query parameters. The request supports pagination (page number, page size) and filtering conditions.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/userExample/listB\xe4\x01\x92A\xa8\x01\x12$\n" +
	"\x1aserverNameExample api docs2\x06v1.0.0\x1a\x0elocalhost:8080*\x02\x01\x022\x10application/json:\x10application/jsonZH\n" +
	"F\n" +
	"\n" +
	"BearerAuth\x128\b\x02\x12#Type Bearer your-jwt-token to Value\x1a\rAuthorization \x02Z6github.com/Eric-Guo/sponge/api/serverNameExample/v1;v1b\x06proto3"

var (
	file_api_serverNameExample_v1_userExample_proto_rawDescOnce sync.Once
	file_api_serverNameExample_v1_userExample_proto_rawDescData []byte
)

func file_api_serverNameExample_v1_userExample_proto_rawDescGZIP() []byte {
	file_api_serverNameExample_v1_userExample_proto_rawDescOnce.Do(func() {
		file_api_serverNameExample_v1_userExample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serverNameExample_v1_userExample_proto_rawDesc), len(file_api_serverNameExample_v1_userExample_proto_rawDesc)))
	})
	return file_api_serverNameExample_v1_userExample_proto_rawDescData
}

var file_api_serverNameExample_v1_userExample_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_serverNameExample_v1_userExample_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_serverNameExample_v1_userExample_proto_goTypes = []any{
	(GenderType)(0),                      // 0: api.serverNameExample.v1.GenderType
	(*CreateUserExampleRequest)(nil),     // 1: api.serverNameExample.v1.CreateUserExampleRequest
	(*CreateUserExampleReply)(nil),       // 2: api.serverNameExample.v1.CreateUserExampleReply
	(*DeleteUserExampleByIDRequest)(nil), // 3: api.serverNameExample.v1.DeleteUserExampleByIDRequest
	(*DeleteUserExampleByIDReply)(nil),   // 4: api.serverNameExample.v1.DeleteUserExampleByIDReply
	(*UpdateUserExampleByIDRequest)(nil), // 5: api.serverNameExample.v1.UpdateUserExampleByIDRequest
	(*UpdateUserExampleByIDReply)(nil),   // 6: api.serverNameExample.v1.UpdateUserExampleByIDReply
	(*UserExample)(nil),                  // 7: api.serverNameExample.v1.UserExample
	(*GetUserExampleByIDRequest)(nil),    // 8: api.serverNameExample.v1.GetUserExampleByIDRequest
	(*GetUserExampleByIDReply)(nil),      // 9: api.serverNameExample.v1.GetUserExampleByIDReply
	(*ListUserExampleRequest)(nil),       // 10: api.serverNameExample.v1.ListUserExampleRequest
	(*ListUserExampleReply)(nil),         // 11: api.serverNameExample.v1.ListUserExampleReply
	(*types.Params)(nil),                 // 12: api.types.Params
}
var file_api_serverNameExample_v1_userExample_proto_depIdxs = []int32{
	0,  // 0: api.serverNameExample.v1.CreateUserExampleRequest.gender:type_name -> api.serverNameExample.v1.GenderType
	0,  // 1: api.serverNameExample.v1.UpdateUserExampleByIDRequest.gender:type_name -> api.serverNameExample.v1.GenderType
	0,  // 2: api.serverNameExample.v1.UserExample.gender:type_name -> api.serverNameExample.v1.GenderType
	7,  // 3: api.serverNameExample.v1.GetUserExampleByIDReply.userExample:type_name -> api.serverNameExample.v1.UserExample
	12, // 4: api.serverNameExample.v1.ListUserExampleRequest.params:type_name -> api.types.Params
	7,  // 5: api.serverNameExample.v1.ListUserExampleReply.userExamples:type_name -> api.serverNameExample.v1.UserExample
	1,  // 6: api.serverNameExample.v1.userExample.Create:input_type -> api.serverNameExample.v1.CreateUserExampleRequest
	3,  // 7: api.serverNameExample.v1.userExample.DeleteByID:input_type -> api.serverNameExample.v1.DeleteUserExampleByIDRequest
	5,  // 8: api.serverNameExample.v1.userExample.UpdateByID:input_type -> api.serverNameExample.v1.UpdateUserExampleByIDRequest
	8,  // 9: api.serverNameExample.v1.userExample.GetByID:input_type -> api.serverNameExample.v1.GetUserExampleByIDRequest
	10, // 10: api.serverNameExample.v1.userExample.List:input_type -> api.serverNameExample.v1.ListUserExampleRequest
	2,  // 11: api.serverNameExample.v1.userExample.Create:output_type -> api.serverNameExample.v1.CreateUserExampleReply
	4,  // 12: api.serverNameExample.v1.userExample.DeleteByID:output_type -> api.serverNameExample.v1.DeleteUserExampleByIDReply
	6,  // 13: api.serverNameExample.v1.userExample.UpdateByID:output_type -> api.serverNameExample.v1.UpdateUserExampleByIDReply
	9,  // 14: api.serverNameExample.v1.userExample.GetByID:output_type -> api.serverNameExample.v1.GetUserExampleByIDReply
	11, // 15: api.serverNameExample.v1.userExample.List:output_type -> api.serverNameExample.v1.ListUserExampleReply
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_serverNameExample_v1_userExample_proto_init() }
func file_api_serverNameExample_v1_userExample_proto_init() {
	if File_api_serverNameExample_v1_userExample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serverNameExample_v1_userExample_proto_rawDesc), len(file_api_serverNameExample_v1_userExample_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_serverNameExample_v1_userExample_proto_goTypes,
		DependencyIndexes: file_api_serverNameExample_v1_userExample_proto_depIdxs,
		EnumInfos:         file_api_serverNameExample_v1_userExample_proto_enumTypes,
		MessageInfos:      file_api_serverNameExample_v1_userExample_proto_msgTypes,
	}.Build()
	File_api_serverNameExample_v1_userExample_proto = out.File
	file_api_serverNameExample_v1_userExample_proto_goTypes = nil
	file_api_serverNameExample_v1_userExample_proto_depIdxs = nil
}
